name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

env:
  FATS_DIR: ".github/workflows/fats"

jobs:

  fats:
    name: FATS
    if: success() && github.event_name == 'push'
    strategy:
      matrix:
        config:
        - os: ubuntu-latest
          qualifier: kind
          cluster: kind
          registry: docker-daemon
      fail-fast: false
    runs-on: ${{ matrix.config.os }}
    env:
      CLUSTER: ${{ matrix.config.cluster }}
      REGISTRY: ${{ matrix.config.registry }}
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Setup env
        run: |
          job=$(date +%s) # TODO use something that is assigned by CI to guarantee uniqueness
          echo "JOB_ID=${job}"
          echo "CLUSTER_NAME=cli-${job}-${{ matrix.config.qualifier }}" >> $GITHUB_ENV
          echo "NAMESPACE=cli-${job}-${{ matrix.config.qualifier }}" >> $GITHUB_ENV
        shell: bash
      - name: Fetch FATS
        run: .github/workflows/fats.sh
        shell: bash
        timeout-minutes: 10
      - name: Build Apps
        run: .github/workflows/build.sh
        shell: bash
        timeout-minutes: 30
      - name: Run Tests
        run: .github/workflows/run.sh
        shell: bash
        timeout-minutes: 30
      - name: Collect diagnostics
        run: ${FATS_DIR}/diagnostics.sh
        shell: bash
        if: always()
        timeout-minutes: 1
      - name: Cleanup Tests
        run: .github/workflows/cleanup.sh
        shell: bash
        if: always()
        timeout-minutes: 10
      - name: Cleanup FATS
        run: ${FATS_DIR}/cleanup.sh
        shell: bash
        if: always()
        timeout-minutes: 30
